services:
  - type: web
    name: opensales-landing
    runtime: node
    plan: free
    rootDir: frontend/landing-page
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "20"
